name: Windows tests

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-venv-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Fix git breaking on purpose
        run: |
          git config --global --add safe.directory '*'
          git config --global protocol.file.allow always

      - name: Sync Terra venv
        run: |
          source setup.env
          just terra sync

      - name: Unit tests
        run: |
          source setup.env
          just terra test
